version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.2
    steps:
      - checkout
      - restore_cache:
          name: Restore dependencies
          key: yarn-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          name: Save dependencies
          key: yarn-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Run test
          command: yarn test
